### PR TITLE
first pass at SSO SAML support, we still need to do some UI design

### PR DESCRIPTION
**Pull request by bcoe**

### CODE REVIEW

**Comment by nexdrew** [comment]
We had briefly talked about fronting the website and other endpoints with nginx or load balancing or something that can route requests to multiple apps, to keep number of "ports open to public" to a minimum. I assume we'll just punt on that for now?

**Comment by bcoe** [comment]
I'm tempted to punt on this for the time being, I think best practice is that we ask folks to selectively place ports on the public internet; I like the idea of reducing the ports, but perhaps we can tackle this when we take on the tickets around adding SSL certificates?

**Comment by nexdrew** [comment]
Ok, sounds good. I assume customers who don't need SAML will be fine without opening port 8082?

**Comment by bcoe** [comment]
@nexdrew :+1: correct, it's completely optional.

**Pull request merged**
